### ISSUE TITLE
It isn't clear if the JS tests are actually running on Travis

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#149]
Maybe it needs an exit error code?

**Comment by sahilshekhawat** [comment]
They do run and even fail. I tried by adding an  failing test https://travis-ci.org/sahilshekhawat/pydy/jobs/64528045#L549
We just need to separate ``cd ../../../../../`` because if tests fail this command will not run
https://github.com/sahilshekhawat/pydy/commit/9689289f0eecac4ea0bbd67952f747203ce039e0#diff-354f30a63fb0907d4ad57269548329e3R43

**Comment by sahilshekhawat** [comment]
Should I raise a PR to update ``.travis.yml``?

**Comment by moorepants** [comment]
If our JS tests currently fail, then not do not update travis yet. We need the JS tests in a function, non-failing order before turning them on on Travis.

**Comment by sahilshekhawat** [comment]
They are currently running on travis, its just that if they fail all the other things will fail as well because the last command i.e. ``cd ../../../../../`` will not be executed. I just want to update that.

**Comment by sahilshekhawat** [comment]
And all our current tests pass.

**Comment by moorepants** [comment]
Ok, if all out current JS tests pass, then you can update the travis file such that it properly exits with a 1 or 0 for the JS tests.
