### ISSUE TITLE
UI doesn't look good in small window sizes

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#35]
_Issue by **[moorepants](https://github.com/moorepants)** from Sunday Feb 23, 2014 at 05:27 GMT_
_Originally opened as https://github.com/pydy/pydy-viz/issues/112_

----

![screenshot from 2014-02-22 17 08 52](https://f.cloud.github.com/assets/276007/2239713/230c962c-9c4b-11e3-8126-bc45009a2da7.png)

**Comment by moorepants** [comment]
@tarzzz What is the status of this?

**Comment by tarzzz** [comment]
This is an issue we need to brainstorm about. The main problem is that, the webgl's "canvas", on which the visualization is drawn, is non-responsive. On increasing/decreasing the screen size, though the buttons and other UI elements seem to adjust themselves accordingly (responsive), but the canvas does not adjusts itself, and hence the whole UI messes up. It is the only non-responsive element in the UI (and also the most crucial element, since it holds the visualization).

**Comment by moorepants** [comment]
Is this still relevant now that you use boostrap?

**Comment by moorepants** [comment]
Is there no way to make the threejs canvas responsive?
