### ISSUE TITLE
issue with pydy 0.3.1 and sympy 1.0.2

### ISSUE THREAD

**Issue by fifi2961** [pydy/pydy#359]
Hey Guys,
There's an issue with pydy 0.3.1 and sympy 1.0.2 when using "System" with Kane's method. I've the error:

constants.remove(dynamicsymbols._t)
KeyError: t

when I run my program a second time. The first time is OK.

On another machine, when using Sympy 0.7.6.1 and pydy 0.3.1, program is OK each time.

Can you help me ?
Thanks

**Comment by jbm950** [comment]
Could you provide an example of the code you're trying to run? My initial thought is it's trying to remove sympy functions of time from your equations of motion but not finding any to remove. It could be that you input everything into `KanesMethod` as SymPy `Symbol` objects instead of using `sympy.physics.mechanics`'s `dynamicsymbols`. I would be able to help better though if a code segment is provided.

**Comment by fifi2961** [comment]
Thank's for your answer and your help. Here is my code.

[gyrometre.py.zip](https://github.com/pydy/pydy/files/418728/gyrometre.py.zip)

**Comment by jbm950** [comment]
The only error I got was kane.kanes_equations() argument order has been swapped (this hasn't displayed on sympy docs online yet because the doc script has been broken for months from what I understand). Once I swapped the input order (bodies before forces) it ran without throwing any errors (oddly enough though it did not produce any graphs either, looks like you did not call `plt.show()`).

```python
d_u_sur_dt = matrice_masse.inv() * efforts
```

This line is equivalent to 

```python
KM.rhs()
``` 

but the latter includes some optimizations and should run faster. What are you meaning when you run it a second time? Like running it independently again? I do not see why this should cause issues. Try changing the argument order mentioned above and see if that helps.

**Comment by fifi2961** [comment]
Thank's for your reply. I changed the order as you told me in kane.kanes_equations(): it doesn't run anyway. 
When I run the code on Spyder (F5) a first time it works very fine and It produces the graphs (even without plt.show(), on my Mac). Everything is OK. I try a second time (F5) and the error appears (idem a third time and so on). I relaunch the interpreter then F5, it runs well and the next F5, the code crashes. It seems that Sympy 1.0.2 causes this problem because with Sympy 0.7.6, on another computer, everything is OK.

**Comment by jbm950** [comment]
Maybe it's a Spyder issue? Have you tried running it from terminal multiple times (if you do this you'll want to add `plt.show()` to the end of your file to see the graphs)?

**Comment by fifi2961** [comment]
I'll try tomorrow because I must leave now.
Thank's for all.

**Comment by fifi2961** [comment]
It's OK when running multiple times from terminal. It's probably a Spyder issue...
